name: Tenant portal CICD run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPO_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t portfolio:latest .

      - name: Run lint
        run: docker run --rm portfolio:latest npm run lint

      - name: Run tests
        run: docker run --rm /portfolio:latest npm test

      - name: Build project
        run: docker run --rm -v ${{ github.workspace }}/dist:/app/dist portfolio:latest npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
